name: Send to Slack
description: "Sends custom JSON data to Slack workflow"
inputs:
  slack_webhook_url:
    description: "Slack webhook URL"
    required: true
  heading:
    description: "Message heading"
    required: true
  message:
    description: "Message text"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
          	"blocks": [
          		{
          			"type": "section",
          			"text": {
          				"type": "mrkdwn",
          				"text": "${{ inputs.heading }}"
          			}
          		},
          		{
          			"type": "section",
          			"text": {
          				"type": "mrkdwn",
          				"text": "${{ inputs.message }}"
          			}
          		}
          	]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
