name: Send to Slack
description: "Sends custom JSON data to Slack workflow"
inputs:
  slack_webhook_url:
    description: "Slack webhook URL"
    required: true
  payload:
    description: 'Message to send'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          ${{ inputs.payload }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
