name: Golden CI Rust

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
