name: deploy-to-env

on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
        default: release

jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        run: echo The environment is dead
      # - name: Terraform Plan
      #   run: echo The environment is ${{ inputs.env }} 
      # - name: Terraform Apply
      #   run: echo The environment is ${{ inputs.env }} 
      # - name: Deploy to runtime
      #   run: echo The environment is ${{ inputs.env }} 