name: Run Terraform and deploy to K8S

on:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'dev'
      terraform-version:
        required: false
        type: string
        default: '1.5.7'
      # image tag
      image-tag:
        required: true
        type: string


jobs:

  terraform-apply:
    name: Run Terraform apply
    runs-on: ubuntu-latest

    # important to specify the environment here so workflow knows where to apply infrastructure changes.
    # default environment to "dev" if it is not passed in through workflow_dispatch manual trigger
    environment: ${{ inputs.env || 'dev' }}

    if: (inputs.env == null || inputs.env == 'dev')
    steps:
      - uses: actions/checkout@v4

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/actions/tf-apply
        with:
          #terraform_sa: ${{ env.TF_SA }}
          terraform_directory: "terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          #workload_identity_provider: ${{ secrets.GOOGLE_CREDENTIALS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
          environment: ${{ vars.ENVIRONMENT_STAGE }}

  deploy:
    name: Deploy to Kubernetes
    needs: terraform-apply
    runs-on: ubuntu-latest

    # important to specify the environment here so workflow knows where to apply infrastructure changes.
    # default environment to "dev" if it is not passed in through workflow_dispatch manual trigger
    environment: ${{ inputs.env || 'dev' }}

    if: (inputs.env == null || inputs.env == 'dev')
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to K8S
        id: deploy-k8s
        run: echo "Deploying to Kubernetes..."
