name: General build and test workflow

on:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'dev'
    outputs:
      image-tag:
        description: "image tag"
        value: ${{ jobs.general-build-and-test.outputs.image-tag }}

jobs:

  general-build-and-test:
    name: Build, Test, release
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}

    # important to specify environment here, defaults to 'dev', so github ations knows where to retrieve the secrets
    environment: ${{ inputs.env || 'dev' }}

    if: (inputs.env == null || inputs.env == 'dev')
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set image tag output
        id: set-image-tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")-$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Print debug info
        run: |
          echo environment is ${{ inputs.env }}
          echo GITHUB_WORKSPACE is $GITHUB_WORKSPACE
          echo image tag is ${{ steps.set-image-tag.outputs.IMAGE_TAG }}
          echo branch name is ${{ github.ref_name }}


      - name: Build, tag, and push image
        id: build-image
        run: echo "Building, tagging and pushing image...."
